# Generated by Django 4.2.8 on 2024-02-10 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PageLogin', '0008_usuario_ultimo_mes_reinicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos_Sin_Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaccion', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('mes_anio', models.CharField(max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageLogin.usuario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
