# Generated by Django 4.2.8 on 2023-12-22 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=16)),
                ('fecha', models.DateTimeField()),
                ('cvv', models.DecimalField(decimal_places=3, max_digits=3)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageLogin.usuario')),
            ],
            options={
                'verbose_name': 'CardUser',
                'verbose_name_plural': 'CardsUsers',
            },
        ),
    ]
