# Generated by Django 4.2.8 on 2023-12-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageLogin', '0004_alter_carduser_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carduser',
            name='cvv',
            field=models.IntegerField(),
        ),
    ]
