# Generated by Django 4.2.8 on 2023-12-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageLogin', '0005_alter_carduser_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
