# Generated by Django 4.2.8 on 2023-12-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageLogin', '0006_usuario_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='presupuesto_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
