# Generated by Django 4.2.8 on 2024-02-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageLogin', '0007_usuario_presupuesto_actual_alter_usuario_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultimo_mes_reinicio',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
