# Generated by Django 4.2.8 on 2023-12-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Financiero', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimientos',
        ),
    ]
