# Generated by Django 4.2.8 on 2024-01-30 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Financiero', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='gasto',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
