# Generated by Django 4.2.8 on 2024-02-06 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Financiero', '0004_movimientos_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='mes_anio',
            field=models.CharField(default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
    ]
